apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-service-postgresql
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: "10.100.186.27"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret-postgresql
type: Opaque
data:
  DB_PASSWORD : bXlwYXNzd29yZA==